apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels: 
     app: nginx 
spec:
  containers:
  - name: mypod
    image: nginx:latest
    env:
    - name: ENVIRONMENT
      value: "development"
    - name: APP_VERSION
      value: "1.0.0"
  # this just a metadata 
    ports:
    - containerPort: 80
